### ISSUE TITLE
Session Initialization Error

### ISSUE THREAD

**Issue by dalliard** [coreymgilmore/stripe-appengine-frontend#1]
Even tough I have 64 characters in the ``session-auth-key.txt``-file, I get the following error:
![2016-12-18-083906_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/21292222/8899e21e-c4fd-11e6-9a53-53eabb864254.png)
I deploy locally with ``goapp serve``, but that shouldn't be a problem?!

**Comment by coreymgilmore** [comment]
Make sure you do not have any whitespace or newlines at the end of the string in this file.  Aka, make sure there isn't a newline entered automatically by your text editor.  The file should be one line long.  Make sure you check the "session-encrypt-key.txt" as well.  Let me know what happens.

I should probably put a `strings.TrimSpace()` in the code when the keys are read from file to remove this issue from occuring.

**Comment by dalliard** [comment]
That's funny, I wanted to show you the files over a gist, downloaded them, copied them into the config folder and they worked. Seems a problem with vim. But why?! No idea. Vim shouldn't add something to the file that doesn't belong there...

**Comment by coreymgilmore** [comment]
I've seen that same thing happen before but with other editors.  I think the editors "add" the extra blank line to signify EOF.  I have updated the code to add the `strings.TrimSpace()` so this doesn't occur in the future.
