### ISSUE TITLE
Invalid API Key provided

### ISSUE THREAD

**Issue by dalliard** [coreymgilmore/stripe-appengine-frontend#2]
I added my public key from stripe in the file `website/js/stripe-public-key.js` in the form of `Stripe.setPublishableKey("thisIsMyPublicKey");`. But when I want to add a new card I get the following error on the website:

````
Invalid API Key provided: nil. This key contains at least one space. Please delete the spaces and try again. If you have any questions, we can help at https://support.stripe.com/.
````

And in the console:

````
2016/12/27 14:51:23 Requesting POST api.stripe.com/v1/customers
2016/12/27 14:51:24 Error encountered from Stripe: {"type":"invalid_request_error","message":"Invalid API Key provided: nil. This key contains at least one space. Please delete the spaces and try again. If you have any questions, we can help at https://support.stripe.com/.","status":401}
2016/12/27 14:51:24 ERROR: output.Error:%!(EXTRA output.errorObj={Title:stripeError Msg:Invalid API Key provided: nil. This key contains at least one space. Please delete the spaces and try again. If you have any questions, we can help at https://support.stripe.com/.})
INFO     2016-12-27 14:51:24,624 module.py:806] default: "POST /card/add/ HTTP/1.1" 400 295
````

I can't figure out by myself what exactly causes this error. As far as I understand it, Stripe doesn't get a public key from me at all. Here an image how it looks in the chrome developer console:

![2016-12-27-155858_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/21502073/81799130-cc4d-11e6-80de-12bb7c19a07f.png)

Any ideas?

**Comment by coreymgilmore** [comment]
Hi there,

So first things first....are you sure you don't have any whitespace in your API key you provided?  A fairly obvious question given the error message.

Second thing...does your key start with "pk_test_" or "pk_live_"?

Third...can you make sure the stripe-public-key.js file is being loaded by going to the "Networking" tab in Chrome's dev tools, refresh the page, and take a look at what is loading.  Screenshot the entire "Networking" tab and add it to this issue.

**Comment by dalliard** [comment]
Hey,

no whitespace as far as I can see. The key starts with "pk_test_". The file looks like this:
![2016-12-30-172908_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/21568546/d96da272-ceb5-11e6-956d-54a46436ba58.png)

The file is loaded:
![2016-12-30-173100_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/21568576/fa8a2a52-ceb5-11e6-8ddc-b6a493d9fd45.png)

Thanks for your time!

**Comment by coreymgilmore** [comment]
Ok, so your file in the editor image above looks fine.  As does the networking tab screenshot.

Now, this may be a rather obvious question...but you are in "test" mode in Stripe, correct?  As in not in "live" mode.

Let's try overriding the stripe-public-key.js file.  Navigate to the "main" page of the website/app, open up Chrome's dev tools, open up the JS console, and type in `Stripe.setPublishableKey("<your_api_key>");` where <your_api_key> is the key in the above image.  Press enter...the console should respond back "undefined" and try to process the charge again.  Doing this should at least tell us that the Stripe.js is working correctly as is your API key.

Please also check the contents of the stripe-public-key.js file in Chrome.  Click on the stripe-public-key.js file in Chrome's dev tools Networking tab and click the "Preview" sub-tab.  The contents should match exactly to your screenshot above.  Feel free to upload a screenshot as well.

Also, please let me know what Stripe API version you are on.  Maybe there was a change and you are on a newer version.  Open the Stripe Dashboard, click on your company name (upper right corner), click on Account Settings, and click on API Keys (or click [this](https://dashboard.stripe.com/account/apikeys).  Let me know what your API version is.

It would also be helpful to make sure the newest version of stripe.js is loading as well.  In the app/website, open the Chrome dev tools, reload the page, and click on the `js.stripe.com/v2` (or just `v2/` link, then click on the Preview sub-tab, and let me know what the version is...should be similar to `/*! stripe-js 29-11-2016 */

Kind of puked a lot of stuff here...let me know how it goes.

**Comment by dalliard** [comment]
- Stripe mode is "test".

- `Stripe.key`:
![2017-01-01-145526_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/21581460/20415e04-d033-11e6-86d0-d0efccee1c81.png)

- Content of `stripe-public-key.js`:
![2017-01-01-145517_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/21581463/3e86a05e-d033-11e6-8ee3-bafe66152ba1.png)


- I've overwritten the API key in the console but still get the same error.

- The Stripe API version is `2016-07-06 (latest)`.

- Stripe.js version: `/*! stripe-js 29-11-2016 */`

**Comment by coreymgilmore** [comment]
Ok...I am on a different Stripe API version.  I will upgrade to the version you have and test.  Give me a few days as I am catching up from the holidays.  Bug me if you don't hear back by Monday, the 9th.

**Comment by coreymgilmore** [comment]
So I dug into this a bit more and upgraded to the same Stripe API version you are not....that isn't the issue.

Looks like this actually has to deal with your Stripe secret key in `config/stripe-secret-key.txt`.  Make sure there is no whitespace in this file! Very similar issue to #1 that you opened.  Check and see if you have any whitespace in that file and report back to me (I think you might have a trailing newline or beginning space before the "sk_test".  I already added some code to remove any whitespace from this file but will only push the changes after hearing back from you.

Let me know.

**Comment by dalliard** [comment]
Argh, true. Same problem as with #1. Vim adds a `$` at the end of the line with the stripe secret key... Didn't thought about that.

**Comment by coreymgilmore** [comment]
Nice!  Well at least it is an easy fix.  So is everything working properly now?  Should I close this issue?

**Comment by dalliard** [comment]
Hmm, sorry but I just saw, that the file looks like this:
![2017-01-06-204244_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/21730601/c2506d18-d450-11e6-9737-c05456f54526.png)

The `$` is just marking the end of line. Could that be a problem? Maybe you have to add `TrimSpace` as in #1?

**Comment by coreymgilmore** [comment]
What do you mean "edit: I just tried with: "sk_test_....". Same error."?

So, in your screenshot above it shows that there are 33 characters.  Stripe API keys are exactly 32 characters.  So you definitely have an extra character in there somewhere.

I just updated the code to remove any whitespace prior to setting the api key for use.  Pull my changes and give it a test.

Note: just opened my stripe-secret-key.txt file in vim and i don't get the trailing $...(Ubuntu 16.04.1 LTS and Bash for Windows).  What OS are you on? (This doesn't relate to or would cause this issue, just curious).

**Comment by dalliard** [comment]
Oh that is just a vim setting:
![2017-01-06-211653_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/21731643/9cf56ee2-d455-11e6-871b-b8861c4d98ae.png)

Finally it worked with your fix. No idea what vim does there... even without the above setting in my config it seems to add something to the file that is not visible to me.

Thanks!! I close this!

**Comment by coreymgilmore** [comment]
Perfect!  Let me know how it works for you otherwise.
